import type { RegulatoryDocument, Jurisdiction } from "../types.js";

// ─── Types ───────────────────────────────────────────────────────────

export interface RegulatoryQueryResult {
  answer: string;
  confidence: {
    score: number;
    level: "high" | "medium" | "low" | "very_low";
    factors: ConfidenceFactor[];
  };
  citations: Citation[];
  warnings: string[];
  disclaimer: string;
  metadata: {
    sourcesUsed: number;
    sourcesAvailable: number;
    queryTimestamp: string;
    modelUsed: string;
    jurisdiction: string;
  };
}

export interface ConfidenceFactor {
  factor: string;
  score: number;
  description: string;
}

export interface Citation {
  documentId: string;
  documentTitle: string;
  jurisdiction: string;
  publishedAt: string;
  relevanceScore: number;
  verified: boolean;
  excerpt?: string;
}

// ─── Constants ───────────────────────────────────────────────────────

const DISCLAIMER =
  "This analysis is generated by AI and should not be considered legal advice. " +
  "A qualified compliance professional must verify all regulatory interpretations " +
  "before acting on them. Complr's output consists of AI interpretations and is " +
  "not a substitute for final legal judgment.";

const STALE_THRESHOLD_DAYS = 365;

// ─── ConfidenceScorer ────────────────────────────────────────────────

/**
 * Analyzes LLM responses against source documents to produce confidence scores,
 * verify citations, and detect hallucination indicators.
 * Pure logic — no LLM calls.
 */
export class ConfidenceScorer {
  /**
   * Score an LLM response against source documents.
   */
  score(params: {
    answer: string;
    question: string;
    jurisdiction: string;
    sourceDocs: RegulatoryDocument[];
    modelUsed: string;
  }): RegulatoryQueryResult {
    const { answer, question, jurisdiction, sourceDocs, modelUsed } = params;

    // 1. Extract references from the answer
    const references = this.extractReferences(answer);

    // 2. Verify references against source docs
    const citations: Citation[] = [];
    for (const ref of references) {
      const citation = this.verifyReference(ref, sourceDocs);
      if (citation) {
        citations.push(citation);
      }
    }

    // Also add source docs that weren't explicitly cited but were used
    for (const doc of sourceDocs) {
      const alreadyCited = citations.some((c) => c.documentId === doc.id);
      if (!alreadyCited) {
        const relevance = this.contentOverlap(answer, doc.content);
        if (relevance > 0.1) {
          citations.push({
            documentId: doc.id,
            documentTitle: doc.title,
            jurisdiction: doc.jurisdiction,
            publishedAt: doc.publishedAt,
            relevanceScore: relevance,
            verified: true,
            excerpt: this.findRelevantExcerpt(answer, doc.content),
          });
        }
      }
    }

    // 3. Calculate confidence factors
    const sourceCoverage = this.calculateSourceCoverage(answer, sourceDocs);
    const recency = this.calculateRecencyScore(sourceDocs);
    const specificity = this.calculateSpecificityScore(answer, sourceDocs);
    const citationAccuracy = this.calculateCitationAccuracy(references, sourceDocs);

    const factors: ConfidenceFactor[] = [
      {
        factor: "source_coverage",
        score: sourceCoverage,
        description: sourceCoverage >= 0.7
          ? "Answer is well-supported by available regulatory documents"
          : sourceCoverage >= 0.4
            ? "Answer is partially supported by available documents"
            : "Limited source material available for this query",
      },
      {
        factor: "recency",
        score: recency,
        description: recency >= 0.7
          ? "Source documents are recent and likely current"
          : recency >= 0.4
            ? "Some source documents may be outdated"
            : "Source documents may not reflect current regulations",
      },
      {
        factor: "specificity",
        score: specificity,
        description: specificity >= 0.7
          ? "Answer contains specific regulatory details (thresholds, sections, dates)"
          : specificity >= 0.4
            ? "Answer contains some specific details"
            : "Answer is mostly general without specific regulatory references",
      },
      {
        factor: "citation_accuracy",
        score: citationAccuracy,
        description: citationAccuracy >= 0.7
          ? "Referenced documents are verified in the knowledge base"
          : citationAccuracy >= 0.4
            ? "Some references could not be verified"
            : "Most references could not be verified against source documents",
      },
    ];

    // 4. Detect hallucination indicators
    const warnings = this.detectHallucinationIndicators(answer, sourceDocs, jurisdiction);

    // 5. Calculate overall score
    const overallScore = factors.reduce((sum, f) => sum + f.score, 0) / factors.length;
    const level: RegulatoryQueryResult["confidence"]["level"] =
      overallScore >= 0.7 ? "high" :
      overallScore >= 0.5 ? "medium" :
      overallScore >= 0.3 ? "low" : "very_low";

    // Add low-confidence warning
    if (level === "low" || level === "very_low") {
      warnings.push(
        "Low confidence score. This response should be verified by a compliance professional before use."
      );
    }

    return {
      answer,
      confidence: {
        score: Math.round(overallScore * 100) / 100,
        level,
        factors,
      },
      citations: citations.sort((a, b) => b.relevanceScore - a.relevanceScore),
      warnings,
      disclaimer: DISCLAIMER,
      metadata: {
        sourcesUsed: citations.filter((c) => c.verified).length,
        sourcesAvailable: sourceDocs.length,
        queryTimestamp: new Date().toISOString(),
        modelUsed,
        jurisdiction,
      },
    };
  }

  // ─── Reference extraction ──────────────────────────────────────────

  /** Extract document/regulation references from the answer text */
  private extractReferences(text: string): string[] {
    const refs: string[] = [];

    // Match quoted titles: "Payment Services Act", 'AMLO', etc.
    const quotedPattern = /["']([A-Z][^"']{5,80})["']/g;
    let match: RegExpExecArray | null;
    while ((match = quotedPattern.exec(text)) !== null) {
      refs.push(match[1]);
    }

    // Match common regulation patterns: "Section 12", "Article 5", "Part IV"
    const sectionPattern = /(?:Section|Article|Part|Chapter|Regulation|Rule)\s+[\dIVXLCDMivxlcdm]+/gi;
    while ((match = sectionPattern.exec(text)) !== null) {
      refs.push(match[0]);
    }

    // Match act/ordinance names
    const actPattern = /(?:the\s+)?([A-Z][\w\s]+(?:Act|Ordinance|Regulation|Rules|Guidelines|Notice|Code))/g;
    while ((match = actPattern.exec(text)) !== null) {
      refs.push(match[1].trim());
    }

    return [...new Set(refs)];
  }

  /** Verify a reference against source documents */
  private verifyReference(ref: string, docs: RegulatoryDocument[]): Citation | null {
    const refLower = ref.toLowerCase();

    for (const doc of docs) {
      const titleLower = doc.title.toLowerCase();
      const contentLower = doc.content.toLowerCase();

      // Check if reference matches title or appears in content
      const titleMatch = titleLower.includes(refLower) || refLower.includes(titleLower);
      const contentMatch = contentLower.includes(refLower);

      if (titleMatch || contentMatch) {
        return {
          documentId: doc.id,
          documentTitle: doc.title,
          jurisdiction: doc.jurisdiction,
          publishedAt: doc.publishedAt,
          relevanceScore: titleMatch ? 0.9 : 0.7,
          verified: true,
          excerpt: contentMatch ? this.extractExcerptAround(doc.content, ref) : undefined,
        };
      }
    }

    return null;
  }

  // ─── Confidence factor calculations ────────────────────────────────

  /** How well the answer is covered by source documents */
  private calculateSourceCoverage(answer: string, docs: RegulatoryDocument[]): number {
    if (docs.length === 0) return 0;

    // Extract key terms from the answer
    const answerTerms = this.extractKeyTerms(answer);
    if (answerTerms.length === 0) return 0.5;

    // Check how many answer terms appear in source docs
    const allDocText = docs.map((d) => d.content.toLowerCase()).join(" ");
    let matched = 0;
    for (const term of answerTerms) {
      if (allDocText.includes(term.toLowerCase())) matched++;
    }

    return matched / answerTerms.length;
  }

  /** How recent the source documents are */
  private calculateRecencyScore(docs: RegulatoryDocument[]): number {
    if (docs.length === 0) return 0;

    const now = Date.now();
    const scores = docs.map((doc) => {
      const published = new Date(doc.publishedAt).getTime();
      const ageDays = (now - published) / (1000 * 60 * 60 * 24);
      if (ageDays <= 90) return 1.0;
      if (ageDays <= 180) return 0.9;
      if (ageDays <= STALE_THRESHOLD_DAYS) return 0.7;
      if (ageDays <= STALE_THRESHOLD_DAYS * 2) return 0.4;
      return 0.2;
    });

    return scores.reduce((a, b) => a + b, 0) / scores.length;
  }

  /** How specific the answer is (thresholds, dates, section numbers) */
  private calculateSpecificityScore(answer: string, docs: RegulatoryDocument[]): number {
    let score = 0;
    let checks = 0;

    // Check for monetary amounts/thresholds
    const hasAmounts = /\$[\d,]+|\d+\s*(?:USD|SGD|HKD|JPY|BTC|ETH)/i.test(answer);
    score += hasAmounts ? 1 : 0;
    checks++;

    // Check for specific dates or deadlines
    const hasDates = /\d{4}|\d{1,2}\s+(?:January|February|March|April|May|June|July|August|September|October|November|December)/i.test(answer);
    score += hasDates ? 1 : 0;
    checks++;

    // Check for section/article references
    const hasSections = /(?:Section|Article|Part|Chapter)\s+[\dIVX]/i.test(answer);
    score += hasSections ? 1 : 0;
    checks++;

    // Check for specific entity names (regulators, acts)
    const hasEntities = /(?:MAS|SFC|FSA|JVCEA|AMLO|Payment Services Act)/i.test(answer);
    score += hasEntities ? 1 : 0;
    checks++;

    // Verify specifics against source docs
    if (docs.length > 0 && hasAmounts) {
      const amounts = answer.match(/\$[\d,]+|\d+\s*(?:USD|SGD|HKD|JPY)/gi) ?? [];
      const allDocText = docs.map((d) => d.content).join(" ");
      let verified = 0;
      for (const amount of amounts) {
        if (allDocText.includes(amount)) verified++;
      }
      if (amounts.length > 0) {
        score += verified / amounts.length;
        checks++;
      }
    }

    return checks > 0 ? score / checks : 0.5;
  }

  /** How many cited references can be verified */
  private calculateCitationAccuracy(references: string[], docs: RegulatoryDocument[]): number {
    if (references.length === 0) return 0.5; // Neutral if no citations

    let verified = 0;
    for (const ref of references) {
      if (this.verifyReference(ref, docs)) verified++;
    }

    return verified / references.length;
  }

  // ─── Hallucination detection ───────────────────────────────────────

  private detectHallucinationIndicators(
    answer: string,
    docs: RegulatoryDocument[],
    jurisdiction: string
  ): string[] {
    const warnings: string[] = [];

    // Check for references to documents not in the source set
    const references = this.extractReferences(answer);
    const unverified = references.filter((ref) => !this.verifyReference(ref, docs));
    if (unverified.length > 0) {
      warnings.push(
        `Unverified references found: ${unverified.slice(0, 3).join(", ")}${unverified.length > 3 ? ` (+${unverified.length - 3} more)` : ""}. These could not be matched to documents in the knowledge base.`
      );
    }

    // Check for wrong-jurisdiction references
    const jurisdictionMap: Record<string, string[]> = {
      MAS: ["singapore", "mas", "payment services act", "sgd"],
      SFC: ["hong kong", "sfc", "amlo", "hkd", "aspire"],
      FSA: ["japan", "fsa", "jvcea", "jpy", "financial instruments"],
    };
    const otherJurisdictions = Object.entries(jurisdictionMap)
      .filter(([j]) => j !== jurisdiction);

    const answerLower = answer.toLowerCase();
    for (const [otherJ, terms] of otherJurisdictions) {
      const mentionsOther = terms.some((t) => answerLower.includes(t));
      const hasOtherDocs = docs.some((d) => d.jurisdiction === otherJ);
      if (mentionsOther && !hasOtherDocs) {
        warnings.push(
          `Answer references ${otherJ} jurisdiction content but no ${otherJ} documents were in the source context.`
        );
      }
    }

    // Check for confident language about uncertain topics
    const confidentPhrases = [
      "definitely", "certainly", "guaranteed", "always", "never",
      "100%", "absolutely", "without exception", "in all cases",
    ];
    const usesConfidentLanguage = confidentPhrases.some((p) => answerLower.includes(p));
    if (usesConfidentLanguage) {
      warnings.push(
        "Answer uses absolute language (e.g., 'always', 'never', 'guaranteed'). " +
        "Regulatory interpretations typically involve nuance and exceptions."
      );
    }

    // Check if source material was too sparse
    if (docs.length === 0) {
      warnings.push(
        "No source documents were available for this query. The response is based entirely on the model's training data and may not reflect current regulations."
      );
    } else if (docs.length === 1) {
      warnings.push(
        "Only one source document was available. Cross-referencing with additional sources is recommended."
      );
    }

    return warnings;
  }

  // ─── Utility methods ───────────────────────────────────────────────

  /** Extract key terms (multi-word phrases and important single words) */
  private extractKeyTerms(text: string): string[] {
    const stopWords = new Set([
      "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
      "have", "has", "had", "do", "does", "did", "will", "would", "could",
      "should", "may", "might", "shall", "can", "to", "of", "in", "for",
      "on", "with", "at", "by", "from", "as", "into", "through", "during",
      "before", "after", "above", "below", "between", "under", "this", "that",
      "these", "those", "and", "but", "or", "nor", "not", "no", "if", "then",
      "than", "when", "where", "which", "who", "whom", "what", "how", "all",
      "each", "every", "both", "few", "more", "most", "other", "some", "such",
      "only", "own", "same", "so", "also", "very", "just", "about", "it",
    ]);

    const words = text.toLowerCase().match(/\b[a-z]{3,}\b/g) ?? [];
    return [...new Set(words.filter((w) => !stopWords.has(w)))].slice(0, 50);
  }

  /** Calculate overlap between answer and document content */
  private contentOverlap(answer: string, content: string): number {
    const answerTerms = this.extractKeyTerms(answer);
    if (answerTerms.length === 0) return 0;
    const contentLower = content.toLowerCase();
    let matched = 0;
    for (const term of answerTerms) {
      if (contentLower.includes(term)) matched++;
    }
    return matched / answerTerms.length;
  }

  /** Extract a text excerpt around a reference */
  private extractExcerptAround(content: string, ref: string): string | undefined {
    const idx = content.toLowerCase().indexOf(ref.toLowerCase());
    if (idx === -1) return undefined;
    const start = Math.max(0, idx - 100);
    const end = Math.min(content.length, idx + ref.length + 100);
    const excerpt = content.slice(start, end).trim();
    return (start > 0 ? "..." : "") + excerpt + (end < content.length ? "..." : "");
  }

  /** Find the most relevant excerpt from a document for the given answer */
  private findRelevantExcerpt(answer: string, content: string): string | undefined {
    const terms = this.extractKeyTerms(answer).slice(0, 5);
    for (const term of terms) {
      const excerpt = this.extractExcerptAround(content, term);
      if (excerpt) return excerpt;
    }
    return undefined;
  }
}
